version: '3'
services:
  datadog-agent:
    container_name: datadog-agent
    image: datadog/agent:7
    environment:
      - DD_API_KEY=f64996f97fa975602d0c5c0aa9293b2a
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_SITE=ap1.datadoghq.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro 
    ports:
      - 8125:8125/udp
      - 8126:8126/tcp

